apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: shared-volume
          mountPath: /usr/share/nginx/html
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo 'Hello world! this is a shared volume data' > /data/shared-file.txt && sleep 1000"]
      volumeMounts:
        - name: shared-volume
          mountPath: /data
  volumes:
    - name: shared-volume
      emptyDir: 
        sizeLimit: 500Mi
        medium: Memory
