apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
  label: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  volumes:
  - name: scratch-volume
    emptyDir:
      sizeLimit: 500Mi
