apiVersion: v1
kind: PersistentVolumeClaim  # <--- Changed from PersistentVolume
metadata:
  name: mealie-data-pvc      # typically ends in -pvc
  namespace: stevens         # <--- VALID now!
spec:
  accessModes:
    - ReadWriteOnce          # "I need a drive that locks to one node"
  resources:                 # <--- VALID now! (PVs use 'capacity')
    requests:
      storage: 500Mi         # "I need at least 500Mi of space"
  # storageClassName: local-path # This is the default for Rancher Desktop/k3s.
  storageClassName: standard # <--- CHANGED: Minikube's default class name Use 'standard' for most managed k8s services