apiVersion: v1
kind: Service
metadata:
  name: mealie-service
  namespace: stevens
spec:
  selector:
    app.kubernetes.io/name: mealie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer

