apiVersion: v1
kind: Service
metadata:
  name: mealie-service
  namespace: stevens
spec:
  selector:
    # app.kubernetes.io/name: mealie # Refers to the deployment label
    app: mealie # Refers to the pod label, as defined in deploy-mealie.yaml. Needed for proper routing.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer

